<?php

namespace Database\Seeders;

use App\Models\Plan;
use Illuminate\Database\Seeder;

class PlanSeeder extends Seeder
{
    public function run(): void
    {
        $plans = [
            [
                'name'                  => 'Free Trial',
                'slug'                  => 'free',
                'type'                  => 'free',
                'billing_cycle'         => 'one_time',
                'price'                 => 0.00,
                'credits_included'      => 100,
                'price_per_credit'      => 0,
                'api_rate_limit'        => 10,
                'bulk_limit'            => 1000,
                'smtp_validation'       => true,
                'ai_scoring'            => false,
                'webhook_support'       => false,
                'white_label'           => false,
                'reseller_access'       => false,
                'priority_support'      => false,
                'max_team_members'      => 1,
                'max_api_keys'          => 1,
                'is_active'             => true,
                'is_visible'            => true,
                'sort_order'            => 1,
            ],
            [
                'name'                  => 'Starter',
                'slug'                  => 'starter',
                'type'                  => 'starter',
                'billing_cycle'         => 'monthly',
                'price'                 => 19.00,
                'credits_included'      => 5000,
                'price_per_credit'      => 0.005,
                'api_rate_limit'        => 30,
                'bulk_limit'            => 50000,
                'smtp_validation'       => true,
                'ai_scoring'            => false,
                'webhook_support'       => false,
                'white_label'           => false,
                'reseller_access'       => false,
                'priority_support'      => false,
                'max_team_members'      => 1,
                'max_api_keys'          => 3,
                'is_active'             => true,
                'is_visible'            => true,
                'sort_order'            => 2,
                'features'              => ['csv_export', 'api_access'],
            ],
            [
                'name'                  => 'Professional',
                'slug'                  => 'professional',
                'type'                  => 'professional',
                'billing_cycle'         => 'monthly',
                'price'                 => 79.00,
                'credits_included'      => 50000,
                'price_per_credit'      => 0.002,
                'api_rate_limit'        => 60,
                'bulk_limit'            => 1000000,
                'smtp_validation'       => true,
                'ai_scoring'            => true,
                'webhook_support'       => true,
                'white_label'           => false,
                'reseller_access'       => false,
                'priority_support'      => false,
                'max_team_members'      => 5,
                'max_api_keys'          => 10,
                'is_active'             => true,
                'is_visible'            => true,
                'sort_order'            => 3,
                'features'              => ['csv_export', 'xlsx_export', 'api_access', 'webhooks', 'ai_scoring'],
            ],
            [
                'name'                  => 'Enterprise',
                'slug'                  => 'enterprise',
                'type'                  => 'enterprise',
                'billing_cycle'         => 'monthly',
                'price'                 => 299.00,
                'credits_included'      => 500000,
                'price_per_credit'      => 0.0005,
                'api_rate_limit'        => 1000,
                'bulk_limit'            => 10000000,
                'smtp_validation'       => true,
                'ai_scoring'            => true,
                'webhook_support'       => true,
                'white_label'           => true,
                'reseller_access'       => false,
                'priority_support'      => true,
                'max_team_members'      => 25,
                'max_api_keys'          => 50,
                'is_active'             => true,
                'is_visible'            => true,
                'sort_order'            => 4,
                'features'              => ['csv_export', 'xlsx_export', 'json_export', 'api_access', 'webhooks', 'ai_scoring', 'white_label', 'priority_support', 'sla'],
            ],
            [
                'name'                  => 'Reseller',
                'slug'                  => 'reseller',
                'type'                  => 'enterprise',
                'billing_cycle'         => 'monthly',
                'price'                 => 499.00,
                'credits_included'      => 2000000,
                'price_per_credit'      => 0.0002,
                'api_rate_limit'        => 5000,
                'bulk_limit'            => 10000000,
                'smtp_validation'       => true,
                'ai_scoring'            => true,
                'webhook_support'       => true,
                'white_label'           => true,
                'reseller_access'       => true,
                'priority_support'      => true,
                'max_team_members'      => 999,
                'max_api_keys'          => 999,
                'is_active'             => true,
                'is_visible'            => false,
                'sort_order'            => 5,
            ],
        ];

        foreach ($plans as $plan) {
            Plan::updateOrCreate(['slug' => $plan['slug']], $plan);
        }
    }
}
